spring:
  application:
    name: food-flow
  datasource:
    url: jdbc:postgresql://localhost:5432/food_flow
    username: postgres
    password: admin1234
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

minio:
  endpoint: http://localhost:9000
  access-key: admin
  secret-key: password123
  bucket-name: food-flow
  expiry-hours: 24

server:
  address: 0.0.0.0
  port: 8080